### ISSUE TITLE
FAILURE to load G-CODE from known GOOD FILE

### ISSUE THREAD

**Issue by haldean** [jherrm/gcode-viewer#1]
Mr Herrman,

Good Day sir. This G-Code File, as seen on a poster in the Plethora office,cannot be loaded by your **''G-Code Viewer''**. Please improve the G-Code vis-
ualizer until we can visualize this G-Code Quickly and Efficiently. Thank you,

Haldean Brown
_Plethora, Inc_

G-Code is on GOOGLE DRIVE: https://drive.google.com/open?id=0B5niJtxKLNMVaXVnYm9TaGF2blU&authuser=1

**Comment by haldean** [comment]
FOR MORE INFORMATION here is the **''developer console''** output

![image](https://cloud.githubusercontent.com/assets/187501/5930624/b38d9812-a646-11e4-8ba2-5a89483e8727.png)

**Comment by jherrm** [comment]
Mr. Brown,
Suspiciously, after you filed this issue, the one of the bicycle pedals you provided me failed. Since I don't negotiate with terrorists, I'm closing this issue.
![1](https://cloud.githubusercontent.com/assets/327081/5944820/cc481592-a6de-11e4-85a7-badacfaa947e.jpg)
